# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -l cpu_arch='haswell|skylake'
#$ -cwd
#$ -j y
#$ -N assembly_qc
#$ -o assembly_qc.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate quast
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
quast ../data/working/Coral1_assembly_complex/Coral1.contigs.fa -o ../data/results/quast_output_Coral1-complex
quast ../data/working/T3-21-Mmea_assembly/T3-21-Mmea.contigs.fa -o ../data/results/quast_output_T3-21-Mmea
#
echo = `date` job $JOB_NAME done
