# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=128G,h_data=8G,h_vmem=8G
#$ -l cpu_arch='haswell|skylake'
#$ -cwd
#$ -j y
#$ -N Mapping_try1
#$ -o ../logs/Mapping_try1.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate anvio-7.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
#missing two directories that aren't manually made
mkdir /scratch/genomics/stegmannt/metagenomes/first_data/03_mapping/data/bowtie-index/T3-4-Past
mkdir /scratch/genomics/stegmannt/metagenomes/first_data/03_mapping/data/bowtie-index/T3-21-Mmea
#now make indexes for all remaining corals
#Coral1 was done manually up to here
bowtie2-build /scratch/genomics/stegmannt/metagenomes/first_data/02_assembly/contigs-anvio/Coral2.contigs-fixed.fa ../data/bowtie-index/Coral2
bowtie2-build /scratch/genomics/stegmannt/metagenomes/first_data/02_assembly/contigs-anvio/Coral4.contigs-fixed.fa ../data/bowtie-index/Coral4
bowtie2-build /scratch/genomics/stegmannt/metagenomes/first_data/02_assembly/contigs-anvio/Coral5.contigs-fixed.fa ../data/bowtie-index/Coral5
bowtie2-build /scratch/genomics/stegmannt/metagenomes/first_data/02_assembly/contigs-anvio/T3-21-Mmea.contigs-fixed.fa ../data/bowtie-index/T3-21-Mmea
bowtie2-build /scratch/genomics/stegmannt/metagenomes/first_data/02_assembly/contigs-anvio/T3-4-Past_S113_L001.contigs-fixed.fa ../data/bowtie-index/T3-4-Past
#actual mapping stretch
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/Coral1 -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral1_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral1_R2_001_val_2.fq -S ../data/working/Coral1.sam
samtools view -F 4 -bS ../data/working/Coral1.sam > ../data/working/Coral1-RAW.bam
anvi-init-bam ../data/working/Coral1-RAW.bam -o ../data/results/Coral1.bam
rm ../data/working/Coral1-RAW.bam
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/Coral2 -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral2_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral2_R2_001_val_2.fq -S ../data/working/Coral2.sam
samtools view -F 4 -bS ../data/working/Coral2.sam > ../data/working/Coral2-RAW.bam
anvi-init-bam ../data/working/Coral2-RAW.bam -o ../data/results/Coral2.bam
rm ../data/working/Coral2-RAW.bam
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/Coral4 -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral4_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral4_R2_001_val_2.fq -S ../data/working/Coral1.sam
samtools view -F 4 -bS ../data/working/Coral4.sam > ../data/working/Coral4-RAW.bam
anvi-init-bam ../data/working/Coral4-RAW.bam -o ../data/results/Coral4.bam
rm ../data/working/Coral4-RAW.bam
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/Coral5 -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral5_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/Coral5_R2_001_val_2.fq -S ../data/working/Coral5.sam
samtools view -F 4 -bS ../data/working/Coral5.sam > ../data/working/Coral5-RAW.bam
anvi-init-bam ../data/working/Coral5-RAW.bam -o ../data/results/Coral5.bam
rm ../data/working/Coral5-RAW.bam
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/T3-21-Mmea -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/T3-21-Mmea_S96_L001_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/T3-21-Mmea_S96_L001_R2_001_val_2.fq -S ../data/working/T3-21-Mmea.sam
samtools view -F 4 -bS ../data/working/T3-21-Mmea.sam > ../data/working/T3-21-Mmea-RAW.bam
anvi-init-bam ../data/working/T3-21-Mmea-RAW.bam -o ../data/results/T3-21-Mmea.bam
rm ../data/working/T3-21-Mmea-RAW.bam
bowtie2 --threads $NSLOTS -x ../data/bowtie-index/T3-4-Past -1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/T3-4-Past_S113_L001_R1_001_val_1.fq -2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/T3-4-Past_S113_L001_R2_001_val_2.fq -S ../data/working/T3-4-Past.sam
samtools view -F 4 -bS ../data/working/T3-4-Past.sam > ../data/working/T3-4-Past-RAW.bam
anvi-init-bam ../data/working/T3-4-Past-RAW.bam -o ../data/results/T3-4-Past.bam
rm ../data/working/T3-4-Past-RAW.bam
#
echo = `date` job $JOB_NAME done
