# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 40
#$ -q sThC.q
#$ -l mres=320G,h_data=8G,h_vmem=8G
#$ -l cpu_arch='haswell|skylake'
#$ -cwd
#$ -j y
#$ -N megahit_first_data
#$ -o ../logs/megahit_first_data.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate megahit
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
for f in Coral1 Coral2 Coral3 Coral4 Coral5 T3-21Mmea_S96_L001 T3-4-Past_S113_L001
do
megahit \
-1 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/"$f"_R1_001_val_1.fq \
-2 /scratch/genomics/stegmannt/metagenomes/first_data/00_raw/"$f"_R2_001_val_2.fq \
-o ../data/working/assembly_sample_"$f" --out-prefix "$f"
done
#
echo = `date` job $JOB_NAME done
